version: '3'
services:
  zookeeper:
    image: zookeeper:3.6
    environment:
      ZOO_MY_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "imok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  kafka_broker:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_LOG_RETENTION_HOURS: 720
      KAFKA_LOG_RETENTION_BYTES: 100000000000
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mynetwork:
        aliases:
          - kafka_broker

  kafka_producer:
    build: ./kafka
    env_file:
      - ./.env
    command: ["/wait-for-it.sh", "kafka_broker:29092", "--", "python3", "/app/kafka_producer.py"]
    depends_on:
      - kafka_broker
    networks:
      - mynetwork

  spark:
    build: ./spark
    env_file:
      - ./.env
    depends_on:
      - kafka_producer
    networks:
      - mynetwork

  database:
    build: ./database
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    image: mysql:8.2.0
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
  
  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - ./.env
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_SESSION_PROVIDER: "memory"  # Options: memory, database, redis, memcache
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql-data:
  grafana-data: